### Post create Guest
POST localhost:5000/Account/createGuestAccount
Content-Type: application/json

{
}

### Login Guest
POST localhost:5000/Login/guestLogin
Content-Type: application/json

{
    "GuestGuid": "6a8a3734-ec43-40ec-b1f7-d51db336bed7"
}

### create Account
POST localhost:5000/Account/createAccount
Content-Type: application/json

{
    "email": "123@123.com",
    "password": "123"
}

### Login
POST localhost:5000/Login/login/
Content-Type: application/json

{
    "email": "123@123.com",
    "password": "123"
}

### GameEntry
POST localhost:5000/Game/enter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiIxMjNAMTIzLmNvbSIsImp0aSI6ImJkZDQ2NDdlLTExODgtNDViNy1hMTZiLTliYTI2NTNmNzU1MiIsInJvbGUiOiJub3JtYWwiLCJuYmYiOjE3NTQwNTYyMzUsImV4cCI6MTc1NDA1ODAzNSwiaWF0IjoxNzU0MDU2MjM1LCJpc3MiOiJteS1hdXRoLXNlcnZlci5jb20iLCJhdWQiOiJteS1nYW1lLXNlcnZlci5jb20ifQ.hY8WY0xz9f8Jv3Cg_d4y3mCy_MdR9EfQgJaLHXOZUs4

{

}

### NickName
POST localhost:5000/User/nickname
Content-Type: application/json

{
    "userId": 2,
    "nickname": "새로운닉네임",
    "authToken": "d16c921b-cb1e-4359-992f-0e054d598b91"
}