### Post create Guest
POST localhost:5000/Account/createGuestAccount
Content-Type: application/json

{
}



### Login Guest
POST localhost:5000/Login/guestLogin
Content-Type: application/json

{
    "GuestGuid": "79c62a79-8092-4355-94c7-cee5a40d889f"
}


