@RTWWebServer_HostAddress = http://localhost:5006
### Login
POST {{RTWWebServer_HostAddress}}/Auth/login/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### GuestLogin
POST  {{RTWWebServer_HostAddress}}/Auth/guestLogin/